/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as HelpdeskRouteImport } from './routes/helpdesk'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PhonecallsRouteImport } from './routes/phonecalls'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SettingsApiRouteImport } from './routes/settings-api'
import { Route as VehiclesRouteImport } from './routes/vehicles'
import { Route as AppointmentsIndexRouteImport } from './routes/appointments/index'
import { Route as AppointmentsAppointmentIdRouteImport } from './routes/appointments/$appointmentId'
import { Route as AppointmentsCreateRouteImport } from './routes/appointments/create'
import { Route as ContactsContactIdRouteImport } from './routes/contacts.$contactId'
import { Route as HelpdeskTicketIdRouteImport } from './routes/helpdesk.$ticketId'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge/index'
import { Route as KnowledgeCategoryIdRouteImport } from './routes/knowledge/$categoryId'
import { Route as PhonecallsCallIdRouteImport } from './routes/phonecalls.$callId'
import { Route as SalesIndexRouteImport } from './routes/sales/index'
import { Route as SalesCreateRouteImport } from './routes/sales/create'
import { Route as SettingsBranchesRouteImport } from './routes/settings/branches'
import { Route as SettingsCompaniesRouteImport } from './routes/settings/companies'
import { Route as SettingsDefinitionsRouteImport } from './routes/settings/definitions'
import { Route as SettingsEngineersRouteImport } from './routes/settings/engineers'
import { Route as SettingsGeneralSettingsRouteImport } from './routes/settings/general-settings'
import { Route as SettingsMailGroupsRouteImport } from './routes/settings/mail-groups'
import { Route as SettingsPageAccessRouteImport } from './routes/settings/page-access'
import { Route as SettingsRolesRouteImport } from './routes/settings/roles'
import { Route as SettingsStationsRouteImport } from './routes/settings/stations'
import { Route as SettingsUsersRouteImport } from './routes/settings/users'
import { Route as SettingsWarrantyPackagesRouteImport } from './routes/settings/warranty-packages'
import { Route as VehiclesVehicleIdRouteImport } from './routes/vehicles.$vehicleId'
import { Route as SystemRouteImport } from './routes/system'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpdeskRoute = HelpdeskRouteImport.update({
  id: '/helpdesk',
  path: '/helpdesk',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PhonecallsRoute = PhonecallsRouteImport.update({
  id: '/phonecalls',
  path: '/phonecalls',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsApiRoute = SettingsApiRouteImport.update({
  id: '/settings-api',
  path: '/settings-api',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsIndexRoute = AppointmentsIndexRouteImport.update({
  id: '/appointments/',
  path: '/appointments/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsAppointmentIdRoute =
  AppointmentsAppointmentIdRouteImport.update({
    id: '/appointments/$appointmentId',
    path: '/appointments/$appointmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppointmentsCreateRoute = AppointmentsCreateRouteImport.update({
  id: '/appointments/create',
  path: '/appointments/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsContactIdRoute = ContactsContactIdRouteImport.update({
  id: '/$contactId',
  path: '/$contactId',
  getParentRoute: () => ContactsRoute,
} as any)
const HelpdeskTicketIdRoute = HelpdeskTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => HelpdeskRoute,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/knowledge/',
  path: '/knowledge/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeCategoryIdRoute = KnowledgeCategoryIdRouteImport.update({
  id: '/knowledge/$categoryId',
  path: '/knowledge/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const PhonecallsCallIdRoute = PhonecallsCallIdRouteImport.update({
  id: '/$callId',
  path: '/$callId',
  getParentRoute: () => PhonecallsRoute,
} as any)
const SalesIndexRoute = SalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesCreateRoute = SalesCreateRouteImport.update({
  id: '/sales/create',
  path: '/sales/create',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBranchesRoute = SettingsBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCompaniesRoute = SettingsCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDefinitionsRoute = SettingsDefinitionsRouteImport.update({
  id: '/definitions',
  path: '/definitions',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsEngineersRoute = SettingsEngineersRouteImport.update({
  id: '/engineers',
  path: '/engineers',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralSettingsRoute = SettingsGeneralSettingsRouteImport.update({
  id: '/general-settings',
  path: '/general-settings',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMailGroupsRoute = SettingsMailGroupsRouteImport.update({
  id: '/mail-groups',
  path: '/mail-groups',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPageAccessRoute = SettingsPageAccessRouteImport.update({
  id: '/page-access',
  path: '/page-access',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsRolesRoute = SettingsRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsStationsRoute = SettingsStationsRouteImport.update({
  id: '/stations',
  path: '/stations',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsWarrantyPackagesRoute =
  SettingsWarrantyPackagesRouteImport.update({
    id: '/warranty-packages',
    path: '/warranty-packages',
    getParentRoute: () => SettingsRoute,
  } as any)
const VehiclesVehicleIdRoute = VehiclesVehicleIdRouteImport.update({
  id: '/$vehicleId',
  path: '/$vehicleId',
  getParentRoute: () => VehiclesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/branches': typeof BranchesRoute
  '/contacts': typeof ContactsRouteWithChildren
  '/helpdesk': typeof HelpdeskRouteWithChildren
  '/login': typeof LoginRoute
  '/phonecalls': typeof PhonecallsRouteWithChildren
  '/roles': typeof RolesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings-api': typeof SettingsApiRoute
  '/vehicles': typeof VehiclesRouteWithChildren
  '/system': typeof SystemRoute
  '/appointments/$appointmentId': typeof AppointmentsAppointmentIdRoute
  '/appointments/create': typeof AppointmentsCreateRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/helpdesk/$ticketId': typeof HelpdeskTicketIdRoute
  '/knowledge/$categoryId': typeof KnowledgeCategoryIdRoute
  '/phonecalls/$callId': typeof PhonecallsCallIdRoute
  '/sales/create': typeof SalesCreateRoute
  '/settings/branches': typeof SettingsBranchesRoute
  '/settings/companies': typeof SettingsCompaniesRoute
  '/settings/definitions': typeof SettingsDefinitionsRoute
  '/settings/engineers': typeof SettingsEngineersRoute
  '/settings/general-settings': typeof SettingsGeneralSettingsRoute
  '/settings/mail-groups': typeof SettingsMailGroupsRoute
  '/settings/page-access': typeof SettingsPageAccessRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/stations': typeof SettingsStationsRoute
  '/settings/users': typeof SettingsUsersRoute
  '/settings/warranty-packages': typeof SettingsWarrantyPackagesRoute
  '/vehicles/$vehicleId': typeof VehiclesVehicleIdRoute
  '/appointments/': typeof AppointmentsIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/sales/': typeof SalesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/branches': typeof BranchesRoute
  '/contacts': typeof ContactsRouteWithChildren
  '/helpdesk': typeof HelpdeskRouteWithChildren
  '/login': typeof LoginRoute
  '/phonecalls': typeof PhonecallsRouteWithChildren
  '/roles': typeof RolesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings-api': typeof SettingsApiRoute
  '/vehicles': typeof VehiclesRouteWithChildren
  '/appointments/$appointmentId': typeof AppointmentsAppointmentIdRoute
  '/appointments/create': typeof AppointmentsCreateRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/helpdesk/$ticketId': typeof HelpdeskTicketIdRoute
  '/knowledge/$categoryId': typeof KnowledgeCategoryIdRoute
  '/phonecalls/$callId': typeof PhonecallsCallIdRoute
  '/sales/create': typeof SalesCreateRoute
  '/settings/branches': typeof SettingsBranchesRoute
  '/settings/companies': typeof SettingsCompaniesRoute
  '/settings/definitions': typeof SettingsDefinitionsRoute
  '/settings/engineers': typeof SettingsEngineersRoute
  '/settings/general-settings': typeof SettingsGeneralSettingsRoute
  '/settings/mail-groups': typeof SettingsMailGroupsRoute
  '/settings/page-access': typeof SettingsPageAccessRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/stations': typeof SettingsStationsRoute
  '/settings/users': typeof SettingsUsersRoute
  '/settings/warranty-packages': typeof SettingsWarrantyPackagesRoute
  '/vehicles/$vehicleId': typeof VehiclesVehicleIdRoute
  '/appointments': typeof AppointmentsIndexRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/sales': typeof SalesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/branches': typeof BranchesRoute
  '/contacts': typeof ContactsRouteWithChildren
  '/helpdesk': typeof HelpdeskRouteWithChildren
  '/login': typeof LoginRoute
  '/phonecalls': typeof PhonecallsRouteWithChildren
  '/roles': typeof RolesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings-api': typeof SettingsApiRoute
  '/vehicles': typeof VehiclesRouteWithChildren
  '/appointments/$appointmentId': typeof AppointmentsAppointmentIdRoute
  '/appointments/create': typeof AppointmentsCreateRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/helpdesk/$ticketId': typeof HelpdeskTicketIdRoute
  '/knowledge/$categoryId': typeof KnowledgeCategoryIdRoute
  '/phonecalls/$callId': typeof PhonecallsCallIdRoute
  '/sales/create': typeof SalesCreateRoute
  '/settings/branches': typeof SettingsBranchesRoute
  '/settings/companies': typeof SettingsCompaniesRoute
  '/settings/definitions': typeof SettingsDefinitionsRoute
  '/settings/engineers': typeof SettingsEngineersRoute
  '/settings/general-settings': typeof SettingsGeneralSettingsRoute
  '/settings/mail-groups': typeof SettingsMailGroupsRoute
  '/settings/page-access': typeof SettingsPageAccessRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/stations': typeof SettingsStationsRoute
  '/settings/users': typeof SettingsUsersRoute
  '/settings/warranty-packages': typeof SettingsWarrantyPackagesRoute
  '/vehicles/$vehicleId': typeof VehiclesVehicleIdRoute
  '/appointments/': typeof AppointmentsIndexRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/sales/': typeof SalesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/branches'
    | '/contacts'
    | '/helpdesk'
    | '/login'
    | '/phonecalls'
    | '/roles'
    | '/settings'
    | '/settings-api'
    | '/vehicles'
    | '/appointments/$appointmentId'
    | '/appointments/create'
    | '/contacts/$contactId'
    | '/helpdesk/$ticketId'
    | '/knowledge/$categoryId'
    | '/phonecalls/$callId'
    | '/sales/create'
    | '/settings/branches'
    | '/settings/companies'
    | '/settings/definitions'
    | '/settings/engineers'
    | '/settings/general-settings'
    | '/settings/mail-groups'
    | '/settings/page-access'
    | '/settings/roles'
    | '/settings/stations'
    | '/settings/users'
    | '/settings/warranty-packages'
    | '/vehicles/$vehicleId'
    | '/appointments/'
    | '/knowledge/'
    | '/sales/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/branches'
    | '/contacts'
    | '/helpdesk'
    | '/login'
    | '/phonecalls'
    | '/roles'
    | '/settings'
    | '/settings-api'
    | '/vehicles'
    | '/appointments/$appointmentId'
    | '/appointments/create'
    | '/contacts/$contactId'
    | '/helpdesk/$ticketId'
    | '/knowledge/$categoryId'
    | '/phonecalls/$callId'
    | '/sales/create'
    | '/settings/branches'
    | '/settings/companies'
    | '/settings/definitions'
    | '/settings/engineers'
    | '/settings/general-settings'
    | '/settings/mail-groups'
    | '/settings/page-access'
    | '/settings/roles'
    | '/settings/stations'
    | '/settings/users'
    | '/settings/warranty-packages'
    | '/vehicles/$vehicleId'
    | '/appointments'
    | '/knowledge'
    | '/sales'
  id:
    | '__root__'
    | '/'
    | '/branches'
    | '/contacts'
    | '/helpdesk'
    | '/login'
    | '/phonecalls'
    | '/roles'
    | '/settings'
    | '/settings-api'
    | '/vehicles'
    | '/appointments/$appointmentId'
    | '/appointments/create'
    | '/contacts/$contactId'
    | '/helpdesk/$ticketId'
    | '/knowledge/$categoryId'
    | '/phonecalls/$callId'
    | '/sales/create'
    | '/settings/branches'
    | '/settings/companies'
    | '/settings/definitions'
    | '/settings/engineers'
    | '/settings/general-settings'
    | '/settings/mail-groups'
    | '/settings/page-access'
    | '/settings/roles'
    | '/settings/stations'
    | '/settings/users'
    | '/settings/warranty-packages'
    | '/vehicles/$vehicleId'
    | '/appointments/'
    | '/knowledge/'
    | '/sales/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BranchesRoute: typeof BranchesRoute
  ContactsRoute: typeof ContactsRouteWithChildren
  HelpdeskRoute: typeof HelpdeskRouteWithChildren
  LoginRoute: typeof LoginRoute
  PhonecallsRoute: typeof PhonecallsRouteWithChildren
  RolesRoute: typeof RolesRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SettingsApiRoute: typeof SettingsApiRoute
  VehiclesRoute: typeof VehiclesRouteWithChildren
  SystemRoute: typeof SystemRoute
  AppointmentsAppointmentIdRoute: typeof AppointmentsAppointmentIdRoute
  AppointmentsCreateRoute: typeof AppointmentsCreateRoute
  KnowledgeCategoryIdRoute: typeof KnowledgeCategoryIdRoute
  SalesCreateRoute: typeof SalesCreateRoute
  AppointmentsIndexRoute: typeof AppointmentsIndexRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
  SalesIndexRoute: typeof SalesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helpdesk': {
      id: '/helpdesk'
      path: '/helpdesk'
      fullPath: '/helpdesk'
      preLoaderRoute: typeof HelpdeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phonecalls': {
      id: '/phonecalls'
      path: '/phonecalls'
      fullPath: '/phonecalls'
      preLoaderRoute: typeof PhonecallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings-api': {
      id: '/settings-api'
      path: '/settings-api'
      fullPath: '/settings-api'
      preLoaderRoute: typeof SettingsApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/': {
      id: '/appointments/'
      path: '/appointments'
      fullPath: '/appointments/'
      preLoaderRoute: typeof AppointmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/$appointmentId': {
      id: '/appointments/$appointmentId'
      path: '/appointments/$appointmentId'
      fullPath: '/appointments/$appointmentId'
      preLoaderRoute: typeof AppointmentsAppointmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/create': {
      id: '/appointments/create'
      path: '/appointments/create'
      fullPath: '/appointments/create'
      preLoaderRoute: typeof AppointmentsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/$contactId': {
      id: '/contacts/$contactId'
      path: '/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof ContactsContactIdRouteImport
      parentRoute: typeof ContactsRoute
    }
    '/helpdesk/$ticketId': {
      id: '/helpdesk/$ticketId'
      path: '/$ticketId'
      fullPath: '/helpdesk/$ticketId'
      preLoaderRoute: typeof HelpdeskTicketIdRouteImport
      parentRoute: typeof HelpdeskRoute
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/$categoryId': {
      id: '/knowledge/$categoryId'
      path: '/knowledge/$categoryId'
      fullPath: '/knowledge/$categoryId'
      preLoaderRoute: typeof KnowledgeCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phonecalls/$callId': {
      id: '/phonecalls/$callId'
      path: '/$callId'
      fullPath: '/phonecalls/$callId'
      preLoaderRoute: typeof PhonecallsCallIdRouteImport
      parentRoute: typeof PhonecallsRoute
    }
    '/sales/': {
      id: '/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof SalesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/create': {
      id: '/sales/create'
      path: '/sales/create'
      fullPath: '/sales/create'
      preLoaderRoute: typeof SalesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/branches': {
      id: '/settings/branches'
      path: '/branches'
      fullPath: '/settings/branches'
      preLoaderRoute: typeof SettingsBranchesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/companies': {
      id: '/settings/companies'
      path: '/companies'
      fullPath: '/settings/companies'
      preLoaderRoute: typeof SettingsCompaniesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/definitions': {
      id: '/settings/definitions'
      path: '/definitions'
      fullPath: '/settings/definitions'
      preLoaderRoute: typeof SettingsDefinitionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/engineers': {
      id: '/settings/engineers'
      path: '/engineers'
      fullPath: '/settings/engineers'
      preLoaderRoute: typeof SettingsEngineersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general-settings': {
      id: '/settings/general-settings'
      path: '/general-settings'
      fullPath: '/settings/general-settings'
      preLoaderRoute: typeof SettingsGeneralSettingsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/mail-groups': {
      id: '/settings/mail-groups'
      path: '/mail-groups'
      fullPath: '/settings/mail-groups'
      preLoaderRoute: typeof SettingsMailGroupsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/page-access': {
      id: '/settings/page-access'
      path: '/page-access'
      fullPath: '/settings/page-access'
      preLoaderRoute: typeof SettingsPageAccessRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/roles': {
      id: '/settings/roles'
      path: '/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof SettingsRolesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/stations': {
      id: '/settings/stations'
      path: '/stations'
      fullPath: '/settings/stations'
      preLoaderRoute: typeof SettingsStationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/warranty-packages': {
      id: '/settings/warranty-packages'
      path: '/warranty-packages'
      fullPath: '/settings/warranty-packages'
      preLoaderRoute: typeof SettingsWarrantyPackagesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/vehicles/$vehicleId': {
      id: '/vehicles/$vehicleId'
      path: '/$vehicleId'
      fullPath: '/vehicles/$vehicleId'
      preLoaderRoute: typeof VehiclesVehicleIdRouteImport
      parentRoute: typeof VehiclesRoute
    }
  }
}

interface ContactsRouteChildren {
  ContactsContactIdRoute: typeof ContactsContactIdRoute
}

const ContactsRouteChildren: ContactsRouteChildren = {
  ContactsContactIdRoute: ContactsContactIdRoute,
}

const ContactsRouteWithChildren = ContactsRoute._addFileChildren(
  ContactsRouteChildren,
)

interface HelpdeskRouteChildren {
  HelpdeskTicketIdRoute: typeof HelpdeskTicketIdRoute
}

const HelpdeskRouteChildren: HelpdeskRouteChildren = {
  HelpdeskTicketIdRoute: HelpdeskTicketIdRoute,
}

const HelpdeskRouteWithChildren = HelpdeskRoute._addFileChildren(
  HelpdeskRouteChildren,
)

interface PhonecallsRouteChildren {
  PhonecallsCallIdRoute: typeof PhonecallsCallIdRoute
}

const PhonecallsRouteChildren: PhonecallsRouteChildren = {
  PhonecallsCallIdRoute: PhonecallsCallIdRoute,
}

const PhonecallsRouteWithChildren = PhonecallsRoute._addFileChildren(
  PhonecallsRouteChildren,
)

interface SettingsRouteChildren {
  SettingsBranchesRoute: typeof SettingsBranchesRoute
  SettingsCompaniesRoute: typeof SettingsCompaniesRoute
  SettingsDefinitionsRoute: typeof SettingsDefinitionsRoute
  SettingsEngineersRoute: typeof SettingsEngineersRoute
  SettingsGeneralSettingsRoute: typeof SettingsGeneralSettingsRoute
  SettingsMailGroupsRoute: typeof SettingsMailGroupsRoute
  SettingsPageAccessRoute: typeof SettingsPageAccessRoute
  SettingsRolesRoute: typeof SettingsRolesRoute
  SettingsStationsRoute: typeof SettingsStationsRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
  SettingsWarrantyPackagesRoute: typeof SettingsWarrantyPackagesRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsBranchesRoute: SettingsBranchesRoute,
  SettingsCompaniesRoute: SettingsCompaniesRoute,
  SettingsDefinitionsRoute: SettingsDefinitionsRoute,
  SettingsEngineersRoute: SettingsEngineersRoute,
  SettingsGeneralSettingsRoute: SettingsGeneralSettingsRoute,
  SettingsMailGroupsRoute: SettingsMailGroupsRoute,
  SettingsPageAccessRoute: SettingsPageAccessRoute,
  SettingsRolesRoute: SettingsRolesRoute,
  SettingsStationsRoute: SettingsStationsRoute,
  SettingsUsersRoute: SettingsUsersRoute,
  SettingsWarrantyPackagesRoute: SettingsWarrantyPackagesRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface VehiclesRouteChildren {
  VehiclesVehicleIdRoute: typeof VehiclesVehicleIdRoute
}

const VehiclesRouteChildren: VehiclesRouteChildren = {
  VehiclesVehicleIdRoute: VehiclesVehicleIdRoute,
}

const VehiclesRouteWithChildren = VehiclesRoute._addFileChildren(
  VehiclesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BranchesRoute: BranchesRoute,
  ContactsRoute: ContactsRouteWithChildren,
  HelpdeskRoute: HelpdeskRouteWithChildren,
  LoginRoute: LoginRoute,
  PhonecallsRoute: PhonecallsRouteWithChildren,
  RolesRoute: RolesRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SettingsApiRoute: SettingsApiRoute,
  VehiclesRoute: VehiclesRouteWithChildren,
  SystemRoute: SystemRoute,
  AppointmentsAppointmentIdRoute: AppointmentsAppointmentIdRoute,
  AppointmentsCreateRoute: AppointmentsCreateRoute,
  KnowledgeCategoryIdRoute: KnowledgeCategoryIdRoute,
  SalesCreateRoute: SalesCreateRoute,
  AppointmentsIndexRoute: AppointmentsIndexRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
  SalesIndexRoute: SalesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
